### PR TITLE
Update grpcio-compiler dependency

### PR DESCRIPTION
**Pull request by nrc**
And bump the minor version.

Could you publish this soon please (it is to avoid a duplicate dependency in our projects)?

### CODE REVIEW

**Comment by mtp401** [comment]
Is the 5.0 compiler backwards compatible with 4.3?

**Comment by nrc** [comment]
> Is the 5.0 compiler backwards compatible with 4.3?

Yes. It should really have been a 0.4.4 release, but we keep the versions of all the grpc-rs crates in sync and the 0.5 release of grpc-rs (the main crate) is not backwards compatible.

**Comment by mtp401** [comment]
Was waiting for the build to finish, but, looks like it completed and the status never made it back to github: https://travis-ci.org/mtp401/protoc-grpcio/builds/515408932

**Comment by mtp401** [comment]
@nrc 1.0.2 is up on crates :tada:

**Comment by nrc** [comment]
Awesome, thanks!

**Pull request merged**
