### PR TITLE
support serde_derive in grpcio

### PR DESCRIPTION
**Pull request by dwerner**
This is possible with stepancheg/protobuf 2.1+, and https://github.com/pingcap/grpc-rs/pull/248 is now merged. Once they cut a crate > 0.4 this should be included.

### CODE REVIEW

**Comment by dwerner** [comment]
https://github.com/pingcap/grpc-rs/issues/272 is now complete, and the dep is changed to 0.4.3 in this PR

**Comment by mtp401** [comment]
Hey @dwerner thanks the for the PR! Could you rebase out the merge commits in order to keep the git history clean? Additionally, looks like you need to update the example in order for the build to succeed.

**Comment by dwerner** [comment]
Thanks for the review! Sorry for the delay, that should cover the rebase+squash. Let me know if there's anything else, thanks.

**Comment by mtp401** [comment]
@dwerner 1.0.0 is now live on crates.io.

**Comment by dwerner** [comment]
@mtp401 Great, thank you very much!

**Pull request merged**
